scene.onOverlapTile(SpriteKind.Player, sprites.swamp.swampTile0, function (sprite, location) {
    game.over(false)
    tiles.placeOnRandomTile(mySprite, sprites.swamp.swampTile0)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vy = -150
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tilePath3, function (sprite, location) {
    tiles.placeOnRandomTile(mySprite, sprites.builtin.forestTiles6)
    mySprite = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . f f 
        . . . . . . . . . . . . f f . f 
        . . . . . . . . . f f . . f . f 
        . . f f . . . . f f . . . f . f 
        . . . f . . . . f . . . f f . f 
        . . . f f f f f f . . f f . . f 
        . . . . . . f f . . . f . f f f 
        . . 1 1 1 1 f f . . . f . f . . 
        . . 1 2 1 1 f f f f f f f f . . 
        . . f f f f f f f f f f f f . . 
        . . f f f f f f f f f f f f . . 
        . . . . . f f f f f f f f f f . 
        . . . . . f . f . . f . f . . . 
        . . . . . f . f . . f . f . . . 
        `, SpriteKind.Enemy)
    tiles.setTilemap(tilemap`level1`)
})
let mySprite: Sprite = null
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffff555555555555fffffffffffffffffffffffffffffffffffffffffffffffffffffffff777777fffffffffffffffffffffffffaaaaaafffffffffffffffffffffffffff
    fffffffffffffffffffffffffff5555555555555ffffffffffffffffffffffffffffffffffffffffffffffffffffffff7777777ffffffffffffffffffffffffaaaaaafffffffffffffffffffffffffff
    fffffffffffffffffffffffffff555555555555555fffffffffffffffffffffffffffffffffffffffffffff2ffffffff7777777ffffffffffffffffffffffffaaaaaafffffffffffffffffffffffffff
    fffffffffffffffffffffffffff55555555555555555ffffffffffffffffffffffffffffffffffffffffffffffffffff77777777fffffffffffffffffffffffaaaaaaaffffffffffffffffffffffffff
    fffffffffffffffffffffffffff5555555555555555555ffffffffffffffffffffffffffffffffffffffffffffffffff777777777ffffffffffffffffffffffaaaaaaaffffffffffffffffffffffffff
    fffffffffffffffffffffffffff55555555555555555555fffffffffffffffffffffffffffffffffffffffffffffffff777777777ffffffffffffffffffffffaaaaaaaffffffffffffffffffffffffff
    fffffffffffffffffffffffffff555555555555555555555ffffffffffffffffffffffffffffffffffffffffffffffff777777777ffffffffffffffffffffffaaaaaaaafffffffffffffffffffffffff
    fffffffffffffffffffffffffff555555555555555555555ffffffffffffffffffffffffffffffffffffffffffffffff777777777ffffffffffffffffffffffaaaaaaaafffffffffffffffffffffffff
    fffffffffffffffffffffffffff555555ff55555555555555fffffffffffffffffffffffffffffffffffffffffffffff777777777ffffffffffffffffffffffaaaaaaaafffffffffffffffffffffffff
    ffffffffffffffffffffffffff555555fffff555555555555ffffffffffffffffffffffffffffffffffffffffffffffff77777777fffffffffffffffffffffffaaaaaaafffffffffffffffffffffffff
    ffffffffffffffffffffffffff555555fffffff5555555555ffffffffffffffffffffffffffffffffffffffffffffffff77777777ffffffffffffffffffffffffaaaaaaaffffffffffffffffffffffff
    ffffffffffffffffffffffffff555555fffffff5555555555ffffffffffffffffffffffffffffffffffffffffffffffff777777777fffff33333fffffffffffff2aaaaaaffffffffffffffffffffffff
    ffffffffffffffffffffffffff555555ffffffff5555555555fffffffffffffffffffffffffffffffffffffffffffffff777777777fffff33333ffffffffffffffaaaaaaffffffffffffffffffffffff
    ffffffffffffffffffffffffff555555fffffffff555555555ffffffffffffffffffffffffffffffffffffffffffffffff77777777fffff33333ffffffffffffffaaaaaaafffffffffffffffffffffff
    ffffffffffffffffffffffffff555555fffffffffff5555555ffffffffffffffffffffffffffffffffffffffffffffffff77777777fffff33333ffffffffffffffaaaaaaafffffffffffffffffffffff
    ffffffffffffffffffffffffff55555ffffffffffff5555555ffffffffffff9999999999999ffffffffffffffffffffffff77777777ffff33333fffffffffffffffaaaaaafffffffffffffffffffffff
    ffffffffffffffffffffffffff55555ffffffffffff5555555ffffffff999999999999999999fffffffffffffffffffffff77777777ffffffffffffffffffffffffaaaaaaaffffffffffffffffffffff
    ffffffffffffffffffffffffff55555ffffffffffff5555555fffffff99999999999999999999fffffffffffffffffffffff7777777ffffffffffffffffffffffffaaaaaaaffffffffffffffffffffff
    ffffffffffffffffffffffffff55555ffffffffffff5555555fffffff99999999999999999999fffffffffffffffffffffff7777777fffffffffffffffffffffffffaaaaaaafffffffffffffffffffff
    fffffffffffffffffffffffff555555ffffffffffff5555555fffffff99999999999999999999fffffffffffffffffffffff7777777fffffffff333333ffffffffffaaaaaaafffffffffffffffffffff
    ffffffffffffffffffffffff5555555fffffffffff55555555fffffff99999999999999999999fffffffffffffffffffffff7777777fffffffff333333ffffffffffaaaaaaafffffffffffffffffffff
    ffffffffffffffffffffffff55555555ffffffffff55555555fffffff999999999999999999999ffffffffffffffffffffff77777777ffffffff333333fffffffffffaaaaaaaffffffffffffffffffff
    ffffffffffffffffffffffff55555555ffffffffff55555555fffffff999999999999999999999ffffffffffffffffffffff77777777ffffffff333333fffffffffffaaaaaaaffffffffffffffffffff
    ffffffffffffffffffffffff55555555fff555555555555555fffffff999999999999999999999ffffffffffffffffffffff77777777ffffffff333333ffffffffffffaaaaaaffffffffffffffffffff
    ffffffffffffffffffffffff55555555fff555555555555555fffffff9999999999999999999999ffffffffffffffffffffff7777777ffffffff333333ffffffffffffaaaaaaffffffffffffffffffff
    fffffffffffffffffffffffff5555555fff555555555555555ffffffff999999999999999999999fffffffffffffffffffffff7777777fffffff333333ffffffffffffaaaaaaffffffffffffffffffff
    fffffffffffffffffffffffff5555555ff555555555555555fffffffff999999999999999999999fffffffffffffffffffffff7777777fffffff333333fffffffffffffaaaaaffffffffffffffffffff
    fffffffffffffffffffffffff5555555ff55555555555555fffffffffff99999999999999999999fffffffffffffffffffffff7777777fffffff333333fffffffffffffaaaaaffffffffffffffffffff
    ffffffffffffffffffffffffffffffffff555555555555fffffffffffff99999999999999999999fffffffffffffffffffffff7777777fffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffff555555555555fffffffffffff99999999999999999999ffffffffffffffffffffffff777777fffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff444444ffffffffffff55555555555ffffffffffffff99999999999999999999ffffffffffffffffffffffff777777fffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff444444444ffffffffffffffffffffffffffffffffff99999999999999999999ffffffffffffffffffffffff7777777777fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff4444444444fffffffffffffffffffffffffffffffffffff999999ff999999999ffffffffffffffffffffffff7777777777fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff4444444444fffffffffffffffffffffffffffffffffffff999999ff999999999ffffffffffffffffffffffff7777777777fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff4444444444fffffffffffffffffffffffffffffffffffffffffffff999999999ffffffffffffffffffffffff7777777777fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff4444444444fffffffffffffffffffffffffffffffffffffffffffffff999999fffffffffffffffffffffffff7777777777fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff4444444fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777777777ffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff444444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77777777fffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff4444444fffffffffffffffffffffffffffffffffffffffffffdddddddffffffffffffffffffffffffffffffffff777777fffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff4444444ffffffffffffffffffffffffffffffffffffffffffdddddddddfffffffffffffffffffffffffffffffff77777ffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff444444fff4444444fffffffbbbbbbbbbbbffffffffffffffddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff444444fff4444444ffffffbbbbbbbbbbbbbffffffffffffddddddddddddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff444444ff44444444ffffffbbbbbbbbbbbbbbfffffffffffdddddddddddddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff444444ff44444444ffffffbbbbbbbbbbbbbbffffffffffddddddddddddddfffffffffffffffffffffffff888888888888fffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff444444ff44444444fffffbbbbbdddddbbbbbbbfffdddddddddddddddddddfddddddffffffffffffffff88888888888888fffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff4444444444444444fffffbbbbbdddddbbbbbbbbffddddddddddddddddddddddddddddffffffffffffff888888888888888ffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff4444444444444444fffbbbbbbbdddddbbbbbbbbffdddddddddddddddddddddddddddddffffffffffff8888888888888888ffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff4444444444444444fffbbbbbbbdddddbbbbbbbbffdddddddddddddddddddddddddddddffffffffffff8888888888888888ffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff444444444444444ffffbbbbbbbdddddbbbbbbbbffddddddddddddddddddddddddddddddfffffffffff8888888888888888ffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff444444444444444ffffbbbbbbbbbbbbbbbbbbbbffddddddddddddddddddddddddddddddfffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffff44444444444444ffffbbbbbbbbbbbbbbbbbbbbffdddddddddddddddddddddddddddddddffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff4444444444444fffffbbbbbbbbbbbbbbbbbbbffdddddddddddddfdddddddddddddddddffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffff4444444ffffffbbbbbbbbbbbbfffffffffffddddddddffffdddddddddddddddddffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddfffffddddddddddfddddddffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddddfddddddffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddddddffddddddffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddddddfffdddddffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdddddfffffffffffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff88888888888888888fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888888888888888ffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888888888888fffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff88888888ffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888888888fffffffff8888888fffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888888888888fff888888888fffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888888888888888888888888fffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff88888888888888888888888fffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8888888888888888888888fffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888888888888888888fffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888888888888fffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
game.showLongText("\"on W,A,S,D, you move left right up and down. space bar is to jump", DialogLayout.Bottom)
tiles.setTilemap(tilemap`level1`)
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . 4 3 9 a 5 8 . . . . 
    . . . . . . 4 3 9 a 5 8 . . . . 
    . . . . . . 4 3 9 a 5 8 . . . . 
    . . . . . . 4 3 9 a 5 8 . . . . 
    . . . . . . 4 d d d d 8 . . . . 
    . . . . . . . d f f d . . . . . 
    . . . . . . . d d d d . . . . . 
    . . . . . . . . d d . . . . . . 
    . . . . . . . . d d . . . . . . 
    . . . . . . d 9 9 9 9 d . . . . 
    . . . . . d d 9 9 9 9 d d . . . 
    . . . . . d d 9 9 9 9 d d . . . 
    . . . . . d d 9 9 9 9 d d . . . 
    . . . . . d d 9 9 9 9 d d . . . 
    . . . . . d d 9 9 9 9 d d . . . 
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite, 100, 0)
mySprite.ay = 500
tiles.placeOnRandomTile(mySprite, sprites.builtin.forestTiles18)
